### ISSUE TITLE
AssertionError: cfg.MODEL.BACKBONE.CONV_BODY: V-39-FPN-RETINANET are not registered in registry

### ISSUE THREAD

**Issue by binquanwang** [vov-net/VoVNet-FCOS#2]
hi@stigma0617
when i train the code get error like this,can you help me?thanks

 File "tools/train_net.py", line 180, in <module>
    main()
  File "tools/train_net.py", line 173, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 31, in train
    model = build_detection_model(cfg)
  File "/home/yewei/wbq/FCOS/fcos_core/modeling/detector/detectors.py", line 10, in build_detection_model
    return meta_arch(cfg)
  File "/home/yewei/wbq/FCOS/fcos_core/modeling/detector/generalized_rcnn.py", line 29, in __init__
    self.backbone = build_backbone(cfg)
  File "/home/yewei/wbq/FCOS/fcos_core/modeling/backbone/backbone.py", line 101, in build_backbone
    cfg.MODEL.BACKBONE.CONV_BODY
AssertionError: cfg.MODEL.BACKBONE.CONV_BODY: V-39-FPN-RETINANET are not registered in registry
Traceback (most recent call last):
  File "/home/yewei/anaconda3/envs/fcos/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/yewei/anaconda3/envs/fcos/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yewei/anaconda3/envs/fcos/lib/python3.7/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/yewei/anaconda3/envs/fcos/lib/python3.7/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/yewei/anaconda3/envs/fcos/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--config-file', 'configs/vovnet/fcos_V_39_FPN_1x.yaml']' returned non-zero exit status 1.

**Comment by binquanwang** [comment]
after rebuilt the code, it works

**Comment by binquanwang** [comment]
hi@stigma0617
i can not download the pretrained weight,  the link did not work,can you help me?thanks

**Comment by SamMohel** [comment]
Excuse me . What do you mean by rebuilt code ?
